// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions; 
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlx_54kc96MvZGat2WAH7cg9cYcVoyDUM',
    appId: '1:211149124149:web:7a1991657a432a6456777c',
    messagingSenderId: '211149124149',
    projectId: 'aircraft-performance-calc',
    authDomain: 'aircraft-performance-calc.firebaseapp.com',
    storageBucket: 'aircraft-performance-calc.firebasestorage.app',
    measurementId: 'G-RPFVHM30ZS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCY0GyAsiJbVZTcne0SwMfmSCcPi-aROMc',
    appId: '1:211149124149:android:4b3c616d9eb94e2256777c',
    messagingSenderId: '211149124149',
    projectId: 'aircraft-performance-calc',
    storageBucket: 'aircraft-performance-calc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAyfCHP1HlT80LaecN8BO0Nyba1i2frog',
    appId: '1:211149124149:ios:4dd2380fe64cdceb56777c',
    messagingSenderId: '211149124149',
    projectId: 'aircraft-performance-calc',
    storageBucket: 'aircraft-performance-calc.firebasestorage.app',
    iosBundleId: 'com.example.flightCalc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAyfCHP1HlT80LaecN8BO0Nyba1i2frog',
    appId: '1:211149124149:ios:4dd2380fe64cdceb56777c',
    messagingSenderId: '211149124149',
    projectId: 'aircraft-performance-calc',
    storageBucket: 'aircraft-performance-calc.firebasestorage.app',
    iosBundleId: 'com.example.flightCalc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAlx_54kc96MvZGat2WAH7cg9cYcVoyDUM',
    appId: '1:211149124149:web:20f496d8340d55d856777c',
    messagingSenderId: '211149124149',
    projectId: 'aircraft-performance-calc',
    authDomain: 'aircraft-performance-calc.firebaseapp.com',
    storageBucket: 'aircraft-performance-calc.firebasestorage.app',
    measurementId: 'G-ES0PEXZHFC',
  );
}
